---
title: "Uber Pickups Data Visualization"
author: "Idris Rasheed"
date: "12/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Packages}
library(ggplot2)
library(ggthemes)
library(dplyr)
library(tidyr)
library(lubridate)
library(DT)
library(scales)
```

```{r Data}
#Import data
april = read.csv("uber-raw-data-apr14.csv")
may = read.csv("uber-raw-data-may14.csv")
june = read.csv("uber-raw-data-jun14.csv")
july = read.csv("uber-raw-data-jul14.csv")
aug = read.csv("uber-raw-data-aug14.csv")
sept = read.csv("uber-raw-data-sep14.csv")

#Combining separate datasets into one
uber = rbind(april, may, june, july, aug, sept)
```

```{r}
#Converting dates for data visualization 
uber$Date.Time = as.POSIXct(uber$Date.Time, format = "%m/%d/%Y %H:%M:%S")

uber$Time = format(as.POSIXct(uber$Date.Time, format = "%m/%d/%Y %H:%M:%S"), format="%H:%M:%S")

uber$Date.Time = ymd_hms(uber$Date.Time)

#Adding new columns and converting variable types
uber$day = factor(day(uber$Date.Time))
uber$month = factor(month(uber$Date.Time, label = TRUE))
uber$year = factor(year(uber$Date.Time))
uber$weekday = factor(wday(uber$Date.Time, label = TRUE))
uber$hour = factor(hour(hms(uber$Time)))
uber$minute = factor(minute(hms(uber$Time)))
uber$second = factor(second(hms(uber$Time)))
```

```{r}
#transform dataset to group pickups by hour
hour = uber %>%
           group_by(hour) %>%
               dplyr::summarize(total = n()) 
datatable(hour)
```

```{r}
ggplot(hour, aes(hour, total)) + 
        geom_bar( stat = "identity", fill = "blue", color = "red") +
           ggtitle("Pickups by Hour") +
            theme(legend.position = "none") +
            scale_y_continuous(labels = comma)
```

```{r}
#transform dataset to group pickups by hour and month
month_hour = uber %>%
          group_by(month, hour) %>%
             dplyr::summarize(total = n())
datatable(month_hour)
```

```{r}
ggplot(month_hour, aes(hour, total, fill = month)) +
       geom_bar( stat = "identity") +
          ggtitle("Pickups by Hour and Month") +
           scale_y_continuous(labels = comma)
```

```{r}
#transform dataset to group pickups by day of the week
day_weekday = uber %>%
          group_by(day, weekday) %>%
             dplyr::summarize(total = n()) 
datatable(day_weekday)
```

```{r}
ggplot(day_weekday, aes(weekday, total, fill = weekday)) + 
        geom_bar( stat = "identity", fill = "tomato") +
           ggtitle("Pickups by Day of the Week") +
            theme(legend.position = "none") +
            scale_y_continuous(labels = comma)
```

```{r}
#transform dataset to group pickups by day, month, and day of the week 
daymonth = uber %>%
          group_by(month, day, weekday) %>%
             dplyr::summarize(total = n())
datatable(daymonth)
```

```{r}
ggplot(daymonth, aes(month, total, fill = weekday)) + 
        geom_bar( stat = "identity", position = "dodge") +
           ggtitle("Pickups by Day and Month") +
            scale_y_continuous(labels = comma) +
            scale_fill_manual(values = c("limegreen", "magenta", "slategray", "blue4", "olivedrab", "hotpink", "red"))
```

```{r}
ggplot(uber, aes(Base)) + 
 geom_bar(fill = "tomato") +
 scale_y_continuous(labels = comma) +
 ggtitle("Pickups by Bases")
```

```{r}
ggplot(uber, aes(Base, fill = month)) + 
 geom_bar(position = "dodge") +
 scale_y_continuous(labels = comma) +
 ggtitle("Pickups by Base and Month") +
 scale_fill_manual(values = c("limegreen", "magenta", "blue4", "olivedrab", "hotpink", "red"))
```
```{r}
ggplot(uber, aes(Base, fill = weekday)) + 
 geom_bar(position = "dodge") +
 scale_y_continuous(labels = comma) +
 ggtitle("Pickups by Bases and Day of the Week") +
 scale_fill_manual(values = c("limegreen", "magenta", "slategray", "blue4", "olivedrab", "hotpink", "red"))
```

```{r}
#remove missing values for mapping
uber_na = na.omit(uber)

#set min and max for latitude and longitude for mapping
minLat = min(uber_na$Lat)
maxLat = max(uber_na$Lat)
minLong = min(uber_na$Lon)
maxLong = max(uber_na$Lon)
```

```{r}
ggplot(uber_na,aes(x=Lon,y=Lat,color=Base))+
  geom_point(size=1)+
  scale_x_continuous(limits = c(minLong,maxLong))+
  scale_y_continuous(limits = c(minLat,maxLat))+
  theme_map()+
  ggtitle("Map of Uber Pickups by Base from April 2014 to September 2014 in New York")
```


